### ISSUE TITLE
Job profile (resumes, currently-looking status, etc)

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#118]
```
@rocket jobs set --resume=<link>
@rocket jobs set --applying=true
```

**Comment by bfbachmann** [comment]
tl;dr This may not be worth the effort.

I should note that the usefulness of this is still very much up for debate. @bobheadxi and I thought that it may be better to just forward job opportunities to our members instead of trying to do things the other way around by having some central database of resumes that companies have access to.

**Comment by rwblickhan** [comment]
One Rocket 2-specific note - if we do end up going this route, I suspect it might be better to put this under the `@rocket user` command we already have, rather than creating a whole new command, seeing as how this is basically just more Launch Pad member details.

**Comment by rwblickhan** [comment]
Another Rocket 2-specific consideration - we may want to also store "job type/level", seeing as how some people are looking for full-time and other for internships, and we have developers, designers, business...

**Comment by bobheadxi** [comment]
i dont like this any more
