### ISSUE TITLE
Google drive permissions management

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket2#284]
we should sync emails from teams onto access to folders

**Comment by cheukyin699** [comment]
What????

**Comment by bobheadxi** [comment]
Rocket could create Google Drive folders under the Launch Pad org, and maintain access to these folders based on teams

**Comment by cheukyin699** [comment]
How often is it used? What is the user flow?

**Comment by bobheadxi** [comment]
Teams just use their own drives, and people lose access to things + can't access things

**Comment by rwblickhan** [comment]
Yes, this is something @bobheadxi @frostyshadows and I talked about a few times - @frostyshadows and @bfbachmann were quite insistent we keep using Google Drive since for many things (e.g. meeting minutes) it's somewhat more convenient than Github. Unfortunately there wasn't really a set flow or any kind of permissions management so us poor tech leads had to keep begging for access - Rocket could help out here a bit 😂

**Comment by bobheadxi** [comment]
Since drive is just really addictive it seems, I'd like to tackle this sometime before September... hopefully...
