### ISSUE TITLE
ValidationException occurs upon db access on webhooks

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/rocket2#305]
**Describe the bug**
When GitHub sends team or membership webhooks to Rocket, accessing the database results in this error message:
```
{Time: 2019-05-29 20:18:56, Level: [ERROR], module: app, function: log_exception():1761, message: Exception on /webhook [POST]   exc_info=(<class 'botocore.exceptions.ClientError'>, ClientError('An error occurred (ValidationException) when calling the GetItem operation: The provided key element does not match the schema'), <traceback object at 0x7f14e38ed8c8>)}
```
This results in an internal server error and Rocket doesn't return a proper response.

**To Reproduce**
1. Make sure a GitHub organization is configured to send team and membership webhooks to Rocket
2. Start Rocket with `pipenv run launch`
3. Do any action on GitHub that will cause a team or membership webhook to send (eg. creating a team within the GitHub organization)
4. Observe the logs to see the error

**Expected behavior**
The webhooks handler should not run into an internal server error when serving webhooks.

**Screenshots**

**Additional context**
Here is the full log of me attempting to serve team webhooks. The same thing happens for both membership webhook events, though they are not logged.
[issue.log](https://github.com/ubclaunchpad/rocket2/files/3235411/issue.log)

**Comment by cheukyin699** [comment]
Issue can be reproduced on my end

**Comment by cheukyin699** [comment]
The problem here seems to be that dynamodb expects a string as an argument, whereas the provided `github_id` is an integer. Static typechecking can only go so far, and `GetItem` complains that you are using an integer instead of a string. File `webhook/weebhook.py:194` is an example, where the `id` is an integer, and causes issues.

For the person fixing this, it should be an easy fix. Just convert all the integers to strings.

**Comment by cheukyin699** [comment]
Testing webhooks here reminded me of the documentation issues on setting them up. #306
